language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

services: mongodb

before_script:
  - mkdir data/DoctrineMongoODMModule/Hydrator/ -p
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
  - composer install --dev --prefer-dist

script: vendor/bin/phpunit --configuration module/Diarias/tests/phpunit.xml
