language: php

env:
  - MONGO_VERSION=1.2.12

php:
  - 5.3
  - 5.4

services: mongodb

before_script:
  - mkdir data/DoctrineMongoODMModule/Hydrator/ -p
  - pecl -q install mongo-${MONGO_VERSION} && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - phpenv rehash
  - composer install --dev --prefer-dist

script: vendor/bin/phpunit --configuration module/Diarias/tests/phpunit.xml
